package bjdev.ShowItSelf;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

/*
 * this class will use temporally.
 * */

@Component
public class DatabaseLoader implements CommandLineRunner{
	private final TechnologyCardRepository technologyCardRepository;
	
	@Autowired
	public DatabaseLoader(TechnologyCardRepository technologyCardRepository) {
		this.technologyCardRepository = technologyCardRepository;
	}
	
	public void addData(String name, String iconName, String description) throws Exception{
		this.technologyCardRepository.save(new TechnologyCard(name, iconName, description));
	}
	
	@Override
	public void run(String... strings) throws Exception{
		addData("Spring", "spring", "It used for backend.");
		addData("REST API", "rest api", "This project is using REST API.");
		addData("HATEOAS", "hateoas", "HATEOAS(Hypermedia as the Engine of Application State) is used for providing other links.");
		addData("Gradle", "gradle", "Gradle is modern build tool and it is faster than maven(Referenced by gradle).");
		
		addData("React", "react", "It used for frontend. This grammar based on react-spring guide in spring web site.");
		addData("NodeJs", "nodejs", "Nodejs provides frontend runtime and modules for wepack.");
		addData("NPM", "npm", "NPM(Node Package Manager) is package management tool for frontend.");
		addData("Webpack", "webpack", "Wepack makes many static files single js file. Also it optimizes and makes the js file have less size.");

		addData("AWS", "aws", "Cloud platforms provide a lot of resources including vps, network and storage by on-demand.");
		addData("EC2", "ec2", "t2.micro(1 vcpu and 1GB RAM) instance was used at this time. It will be huge instance for changing to kubernetes.");
		addData("Docker", "docker", "Image build will be occurred automatically when I release new version in github.");
		addData("DockerHub", "docker hub", "Github saves code. Like this, Dockerhub saves docker images.");

		addData("Kubernetes", "kubernetes", "Kubernetes (K8s) is an open-source system for automating deployment, scaling, and management of containerized applications.");
		addData("K3s", "k3s", "K3s is lightweight kubernetes.");
		addData("Nginx", "nginx", "Nginx is web server like Apache. It provides lots of features including load balancing. It works as reverse-proxy and user only meet nginx.");
		addData("Asciidoctor", "asciidoctor", "Asciidoctor is simular to mark down, but it has more compatable features such as making https page and binding pages. Doc page is generated by asciidoctor.");

		addData("Git", "git", "VMS(Version Management System) is very important to manage source and collaborate with co-workers. It also provide github action.");
		addData("Github", "github", "I think github which is hosted by microsoft is center of open sources. It provides a lot of awesome features for developers.");
		addData("Github Action", "github action", "Build is automatically occurred on Azure which hosted by microsoft Whenever pushed to master branch");
		addData("HTTPS", "https", "\'Let's Encrypt\' is a kind of certificate agency and it provides free certificate.");
	}
}
