name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up nodejs
      uses: actions/setup-node@v1.4.3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build asciidoc
      run: ./gradlew asciidoctor
    - name: copy doc file to src
      run: cp build/docs/asciidoc.html src/main/resources/templates/docs.html
    - name: Build code and Webpack with Gradle
      run: ./gradlew webpack build
    - name: clean built
      run: rm -r built/*
    - name: copy jar and public
      run: |
        cp `ls build/libs/*.jar` built
        cp -R public built
    - name: Push
      run: |
        git config --local user.email "bj.max.lim@gmail.com"
        git config --local user.name "byoungjoonim"
        git add built
        git commit -m "[build] built by github action on master branch"
        git push
