name: build, webpack and push

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up nodejs
      uses: actions/setup-node@v1.4.3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and Webpack with Gradle
      run: ./gradlew webpack build
    - name: Push
      run: |
        cp -R build ~/
        git checkout deployment -f
        cp -R ~/build .
        git config --local user.email "bj.max.lim@gmail.com"
        git config --local user.name "byoungjoonim"
        git commit -m "[build] built from dev branch" -a
        git push
