name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up nodejs
      uses: actions/setup-node@v1.4.3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean build
      run: ./gradlw clean
    - name: Build and Webpack with Gradle
      run: ./gradlew webpack build
    - name: Push
      run: |
        git config --local user.email "bj.max.lim@gmail.com"
        git config --local user.name "byoungjoonim"
        git add build
        git commit -m "[build] built from master branch"
        git push
